"use client";

import { ImageIcon, LoaderCircle, RotateCcw, Trash2, Upload, X } from "lucide-react";
import type { Dispatch, FormEvent, RefObject, SetStateAction } from "react";

import type { AgentAttachment, RunDetail, Workspace } from "./shared/contracts";
import { ClientTime, StyledSelect } from "./shared/ui";

type TaskForm = { name: string; workspaceId: string; pipelineType: "text_to_model" | "image_to_model" };
type Confirmation = { title: string; description: string; confirmLabel: string; tone: "warning" | "danger" };

export function RevertDialog({ stageTitle, busy, close, confirm }: { stageTitle: string; busy: boolean; close: () => void; confirm: () => Promise<void> }) {
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) close(); }}><div className="revert-confirm-modal" role="dialog" aria-modal="true" aria-labelledby="revert-confirm-title"><div className="revert-confirm-icon"><RotateCcw size={21} /></div><div className="revert-confirm-copy"><span>流程回滚</span><h2 id="revert-confirm-title">回退到“{stageTitle}”？</h2><p>该阶段及后续阶段的产物引用和流程进度将被清除。</p></div><div className="revert-confirm-actions"><button autoFocus type="button" className="secondary-button" onClick={close} disabled={busy}>取消</button><button type="button" className="warning-button" onClick={() => void confirm()} disabled={busy}><RotateCcw size={16} />{busy ? "回滚中…" : "确认回滚"}</button></div></div></div>;
}

export function CreateTaskDialog({ form, setForm, workspaces, sourceImage, setSourceImage, fileRef, busy, close, submit, readImage }: { form: TaskForm; setForm: Dispatch<SetStateAction<TaskForm>>; workspaces: Workspace[]; sourceImage: AgentAttachment | null; setSourceImage: Dispatch<SetStateAction<AgentAttachment | null>>; fileRef: RefObject<HTMLInputElement | null>; busy: boolean; close: () => void; submit: (event: FormEvent) => Promise<void>; readImage: (file: File, maxBytes: number, label: string, ready: (image: AgentAttachment) => void) => void }) {
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}><form className="create-modal" onSubmit={(event) => void submit(event)}><div className="modal-header"><div><span>新资产</span><h2>创建角色资产</h2></div><button className="icon-button" type="button" onClick={close} aria-label="关闭"><X size={19} /></button></div><label>资产名称<input autoFocus required maxLength={80} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="例如：未来城市女飞行员" /></label><div className="create-form-grid"><div className="create-select-field"><span>工作空间</span><StyledSelect value={form.workspaceId} options={workspaces.map((workspace) => ({ value: workspace.id, label: workspace.name }))} onChange={(value) => setForm({ ...form, workspaceId: value })} ariaLabel="任务所属工作空间" placement="up" /></div><div className="create-select-field"><span>工作流</span><StyledSelect value={form.pipelineType} options={[{ value: "text_to_model", label: "文生图 → T-Pose → 模型 → 绑定" }, { value: "image_to_model", label: "原画 → T-Pose 图 → 模型 → 绑定" }]} onChange={(value) => { const pipelineType = value as TaskForm["pipelineType"]; setForm({ ...form, pipelineType }); if (pipelineType === "text_to_model") setSourceImage(null); }} ariaLabel="任务工作流" placement="up" /></div></div>{form.pipelineType === "image_to_model" && <div className="task-source-upload" role="button" tabIndex={0} onClick={() => fileRef.current?.click()} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") fileRef.current?.click(); }}><input ref={fileRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => { const file = event.target.files?.[0]; if (file) readImage(file, 12 * 1024 * 1024, "角色原画", setSourceImage); event.currentTarget.value = ""; }} /><ImageIcon size={22} /><div><strong>{sourceImage?.name || "上传单体角色原画"}</strong><span>{sourceImage ? "原画已就绪，创建后将使用图生图模型转换 T-Pose" : "PNG、JPEG 或 WebP，最大 12 MB"}</span></div><Upload size={17} /></div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>取消</button><button className="primary-button" disabled={busy || (form.pipelineType === "image_to_model" && !sourceImage)}>{busy ? "创建中…" : "创建资产"}</button></div></form></div>;
}

export function CreateWorkspaceDialog({ form, setForm, busy, close, submit }: { form: { name: string; description: string }; setForm: Dispatch<SetStateAction<{ name: string; description: string }>>; busy: boolean; close: () => void; submit: (event: FormEvent) => Promise<void> }) {
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}><form className="create-modal workspace-create-modal" onSubmit={(event) => void submit(event)}><div className="modal-header"><div><span>新空间</span><h2>创建工作空间</h2></div><button className="icon-button" type="button" onClick={close} aria-label="关闭"><X size={19} /></button></div><label>工作空间名称<input autoFocus required maxLength={80} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="例如：忍者角色系列" /></label><label>说明<textarea rows={4} maxLength={500} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="描述该工作空间要管理的角色、风格或交付目标" /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>取消</button><button className="primary-button" disabled={busy}>{busy ? "创建中…" : "创建工作空间"}</button></div></form></div>;
}

export function EventHistoryDialog({ detail, stageTitles, close }: { detail: RunDetail; stageTitles: string[]; close: () => void }) {
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}><div className="create-modal" style={{ width: "min(760px, 100%)" }}><div className="modal-header"><div><span>活动历史</span><h2>全部历史任务记录</h2></div><button className="icon-button" type="button" onClick={close} aria-label="关闭"><X size={19} /></button></div><p style={{ margin: "-8px 0 16px", color: "var(--muted)", fontSize: "13px" }}>共 {detail.events.length} 条记录，按时间倒序排列。</p><div className="event-list" style={{ maxHeight: "min(62vh, 520px)", overflowY: "auto" }}>{detail.events.length === 0 && <p className="notification-empty">暂无任务记录。</p>}{detail.events.map((item) => <div className="event-item" key={item.id}><span className="event-dot" /><div><strong>{item.message}</strong><span>{stageTitles[item.stage] || "流程"} · <ClientTime value={item.createdAt} /></span></div></div>)}</div><div className="modal-actions" style={{ marginTop: "12px" }}><button type="button" className="secondary-button" onClick={close}>关闭</button></div></div></div>;
}

export function ConfirmationDialog({ confirmation, busy, close, confirm }: { confirmation: Confirmation; busy: boolean; close: () => void; confirm: () => Promise<void> }) {
  return <div className="modal-backdrop ui-confirmation-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) close(); }}><div className={`revert-confirm-modal ui-confirmation-modal ${confirmation.tone}`} role="dialog" aria-modal="true" aria-labelledby="ui-confirmation-title"><div className="revert-confirm-icon">{confirmation.tone === "danger" ? <Trash2 size={21} /> : <RotateCcw size={21} />}</div><div className="revert-confirm-copy"><span>{confirmation.tone === "danger" ? "删除确认" : "操作确认"}</span><h2 id="ui-confirmation-title">{confirmation.title}</h2><p>{confirmation.description}</p></div><div className="revert-confirm-actions"><button autoFocus type="button" className="secondary-button" onClick={close} disabled={busy}>取消</button><button type="button" className={confirmation.tone === "danger" ? "danger-button" : "warning-button"} onClick={() => void confirm()} disabled={busy}>{busy ? <LoaderCircle className="spinning" size={16} /> : confirmation.tone === "danger" ? <Trash2 size={16} /> : <RotateCcw size={16} />}{busy ? "处理中…" : confirmation.confirmLabel}</button></div></div></div>;
}
